// The Brady-Manning Work Index: one thousand jobs in sports, and the jobs
// Worktopia hands out first.
//
// Andrew, 2026-10-01: "look up 1000 sports related jobs. yes 1000. that
// includes the obvious ones like athletes, staff, leagues, and media, but
// then also think about manufacturing, sponsorships, technology,
// communication, marketing, ethics, and more. food. transit, etc."
//
// Twenty-five categories, forty titles each. The smoke run counts them and
// fails on a repeat. The list is readable at /comm118/worksheets/worktopia?index.

export const CATEGORIES = [
  ["Athletes", [
    "Professional football player", "Professional basketball player", "Professional baseball player", "Professional hockey player", "Professional soccer player",
    "Professional golfer", "Professional tennis player", "Professional boxer", "Mixed martial artist", "Professional wrestler",
    "Olympic sprinter", "Marathon runner", "Decathlete", "Competitive swimmer", "Platform diver",
    "Artistic gymnast", "Figure skater", "Speed skater", "Alpine ski racer", "Snowboard halfpipe rider",
    "Track cyclist", "Road cyclist", "Mountain biker", "Triathlete", "Rower",
    "Sailor", "Surfer", "Skateboarder", "Rock climber", "Motocross rider",
    "Formula 1 driver", "NASCAR driver", "IndyCar driver", "Jockey", "Rodeo rider",
    "Lacrosse player", "Rugby player", "Cricketer", "Volleyball player", "Beach volleyball player",
  ]],
  ["Coaching", [
    "Head coach", "Offensive coordinator", "Defensive coordinator", "Special teams coordinator", "Quarterbacks coach",
    "Offensive line coach", "Wide receivers coach", "Running backs coach", "Linebackers coach", "Defensive backs coach",
    "Pitching coach", "Hitting coach", "Bullpen coach", "First base coach", "Third base coach",
    "Bench coach", "Assistant basketball coach", "Player development coach", "Shooting coach", "Goalkeeping coach",
    "Skating coach", "Skills coach", "Position coach", "Quality control coach", "Coaching intern",
    "Strength and conditioning coach", "Speed coach", "Swim coach", "Diving coach", "Gymnastics coach",
    "Track and field coach", "Cross country coach", "Golf instructor", "Tennis coach", "Boxing trainer",
    "Jiu-jitsu instructor", "Ski instructor", "Surf instructor", "Climbing coach", "Esports coach",
  ]],
  ["Team operations and front office", [
    "General manager", "Assistant general manager", "President of basketball operations", "President of baseball operations", "Director of player personnel",
    "Director of pro scouting", "Director of college scouting", "Director of amateur scouting", "International scout", "Advance scout",
    "Area scout", "Scouting coordinator", "Salary cap analyst", "Director of football administration", "Team travel coordinator",
    "Equipment manager", "Assistant equipment manager", "Clubhouse manager", "Clubhouse attendant", "Video coordinator",
    "Director of team operations", "Football operations assistant", "Player engagement director", "Director of player development", "Team chaplain",
    "Team nutritionist", "Team chef", "Team interpreter", "Team historian", "Team photographer",
    "Draft analyst", "Director of analytics", "Minor league operations director", "Farm director", "Roster coordinator",
    "Practice facility manager", "Team security director", "Family programs coordinator", "Alumni relations manager", "Chief of staff to the general manager",
  ]],
  ["League and governing bodies", [
    "League commissioner", "Deputy commissioner", "League president", "Conference commissioner", "Executive director of a players' union",
    "Players' union regional director", "Director of league operations", "Director of competition", "Schedule maker", "League disciplinary officer",
    "Independent arbitrator", "League investigator", "Replay center official", "Rules committee chair", "Competition committee analyst",
    "International federation president", "National governing body CEO", "Olympic committee director", "Anti-doping officer", "Drug testing collector",
    "Athlete classification officer", "Paralympic sport director", "Hall of Fame curator", "League archivist", "Expansion committee consultant",
    "Collective bargaining negotiator", "League policy analyst", "Collegiate conference compliance officer", "Championship director", "Tournament director",
    "World Cup bid director", "Host city liaison", "Event sanctioning officer", "League insurance manager", "Membership services director",
    "League chief medical officer", "League chief technology officer", "Minor league affiliate liaison", "Youth league commissioner", "Officiating department director",
  ]],
  ["Officiating", [
    "Football referee", "Umpire (football)", "Down judge", "Line judge", "Field judge",
    "Side judge", "Back judge", "Replay official", "Home plate umpire", "Base umpire",
    "Basketball referee", "Crew chief", "Basketball official (collegiate)", "Hockey referee", "Hockey linesman",
    "Video goal judge", "Soccer referee", "Assistant referee", "Fourth official", "VAR official",
    "Tennis chair umpire", "Line umpire", "Golf rules official", "Boxing referee", "Boxing judge",
    "MMA referee", "MMA judge", "Gymnastics judge", "Figure skating judge", "Diving judge",
    "Swimming starter", "Track starter", "Finish line judge", "Scorekeeper", "Official scorer",
    "Timekeeper", "Shot clock operator", "Chain crew member", "Officiating supervisor", "Referee assignor",
  ]],
  ["Broadcast and production", [
    "Play-by-play announcer", "Color commentator", "Sideline reporter", "Studio host", "Studio analyst",
    "Rules analyst on air", "Broadcast producer", "Broadcast director", "Associate producer", "Technical director",
    "Replay operator", "Camera operator", "Steadicam operator", "Skycam pilot", "Drone camera pilot",
    "Audio engineer", "Broadcast mixer", "Graphics operator", "Score bug operator", "Telestrator operator",
    "Production truck engineer", "Satellite uplink operator", "Field producer", "Booth runner", "Broadcast stage manager",
    "Lighting director", "Highlights editor", "Feature producer", "Documentary director", "Documentary editor",
    "Radio producer", "Radio board operator", "Podcast producer", "Spanish-language play-by-play announcer", "Public address announcer",
    "Stadium DJ", "In-arena host", "Video board producer", "Video board director", "Closed captioner",
  ]],
  ["Journalism and writing", [
    "Beat writer", "Sports columnist", "Investigative sports reporter", "Sports editor", "Deputy sports editor",
    "Copy editor", "Fact checker", "Features writer", "Long-form sportswriter", "Game recap writer",
    "Sports photographer", "Photo editor", "Wire service reporter", "Sports data journalist", "Sports business reporter",
    "Transactions reporter", "Insider (news breaker)", "Draft writer", "Recruiting reporter", "High school sports reporter",
    "Olympic correspondent", "Boxing writer", "Golf writer", "Tennis writer", "Motorsports journalist",
    "Soccer correspondent", "Sports book author", "Ghostwriter for athletes", "Biographer", "Sports historian",
    "Magazine editor-in-chief", "Managing editor", "Newsletter writer", "Sports blogger", "Fan site editor",
    "Press box steward", "Sports information director", "Assistant sports information director", "Statistician for the press", "Sports librarian",
  ]],
  ["Digital, social and content", [
    "Social media manager", "Social media coordinator", "Community manager", "Content strategist", "Content producer",
    "Short-form video editor", "Motion graphics designer", "Meme and reaction editor", "TikTok producer", "YouTube channel manager",
    "Streamer", "Live stream producer", "Digital content director", "Web producer", "App product manager",
    "UX designer", "UI designer", "Front-end developer", "Email marketing specialist", "Push notification strategist",
    "SEO specialist", "Audience development manager", "Digital analytics manager", "Creator partnerships manager", "Influencer relations manager",
    "Athlete content producer", "Behind-the-scenes videographer", "Photo day coordinator", "Graphic designer", "Illustrator",
    "Animator", "Audio producer for digital", "Caption writer", "Trend analyst", "Fan engagement specialist",
    "Discord moderator", "Subreddit moderator", "Digital archivist", "Live blogger", "Second-screen experience producer",
  ]],
  ["Marketing and brand", [
    "Chief marketing officer", "Vice president of marketing", "Brand manager", "Brand strategist", "Marketing director",
    "Marketing coordinator", "Creative director", "Art director", "Copywriter", "Campaign manager",
    "Advertising account executive", "Media buyer", "Media planner", "Market research analyst", "Consumer insights manager",
    "Promotions manager", "Giveaway coordinator", "Theme night planner", "Game presentation director", "Game presentation coordinator",
    "Mascot performer", "Mascot coordinator", "Cheerleading director", "Dance team choreographer", "Drumline director",
    "Street team lead", "Grassroots marketing manager", "Experiential marketing manager", "Pop-up event producer", "Brand ambassador",
    "Hispanic marketing manager", "International marketing manager", "Youth marketing manager", "Loyalty program manager", "CRM manager",
    "Marketing automation specialist", "Product marketing manager", "Trademark and licensing marketer", "Rebrand project manager", "Marketing intern",
  ]],
  ["Sponsorship and partnerships", [
    "Chief revenue officer", "Vice president of corporate partnerships", "Sponsorship sales director", "Sponsorship sales executive", "Partnership activation manager",
    "Partnership services coordinator", "Sponsorship valuation analyst", "Naming rights negotiator", "Jersey patch sales lead", "Signage inventory manager",
    "Hospitality sales manager", "Partnership marketing manager", "Sponsorship strategist (brand side)", "Sports marketing manager (brand side)", "Athlete endorsement manager",
    "Endorsement deal negotiator", "Shoe company athlete rep", "Apparel partnership manager", "Beverage partnership manager", "Automotive partnership manager",
    "Betting partner liaison", "Airline partnership manager", "Telecom partnership manager", "Financial services partnership manager", "Healthcare partnership manager",
    "Community partnership manager", "Charity partnership coordinator", "Cause marketing manager", "Partnership measurement analyst", "Sponsorship research director",
    "Sponsorship renewal manager", "Partnership creative lead", "Sponsorship compliance coordinator", "Fulfillment coordinator", "Partner events manager",
    "Suite sales director", "Premium seating sales executive", "Partnership intern", "Sponsorship agency account director", "Sponsorship agency planner",
  ]],
  ["Communications and public relations", [
    "Vice president of communications", "Director of communications", "Communications manager", "Communications coordinator", "Press officer",
    "Media relations director", "Media relations manager", "Media credentials coordinator", "Press conference coordinator", "Spokesperson",
    "Crisis communications specialist", "Reputation manager", "Internal communications manager", "Executive communications manager", "Speechwriter",
    "Player media trainer", "Media training consultant", "Public affairs director", "Government relations director", "Lobbyist",
    "Community relations director", "Community relations coordinator", "Foundation director", "Foundation program manager", "Corporate social responsibility manager",
    "Publicist", "Athlete publicist", "Entertainment publicist for sports", "Public relations agency account executive", "PR writer",
    "Media monitoring analyst", "Clipping service analyst", "Press release writer", "Media guide editor", "Game notes writer",
    "Postgame quotes transcriber", "Interview coordinator", "Fan mail coordinator", "Season ticket holder communications manager", "Multilingual communications specialist",
  ]],
  ["Ticketing, sales and fan experience", [
    "Vice president of ticket sales", "Director of ticket sales", "Ticket sales account executive", "Inside sales representative", "Group sales manager",
    "Group sales executive", "Season ticket account manager", "Membership services representative", "Ticket operations manager", "Box office manager",
    "Box office attendant", "Ticket pricing analyst", "Dynamic pricing manager", "Secondary market strategist", "Ticket resale partner manager",
    "Ticket fraud analyst", "Mobile ticketing specialist", "Will call attendant", "Ticket taker", "Usher",
    "Guest services manager", "Guest services representative", "Fan experience director", "Fan experience coordinator", "Accessibility services coordinator",
    "Lost and found attendant", "Fan feedback analyst", "Customer service representative", "Call center supervisor", "Sales trainer",
    "Sales operations analyst", "CRM data analyst", "Fan survey researcher", "Premium experience host", "Meet and greet coordinator",
    "Kids club coordinator", "Fan fest producer", "Tour guide (stadium tours)", "Fan club president", "Supporters' group liaison",
  ]],
  ["Venue and facilities", [
    "Stadium general manager", "Arena general manager", "Director of stadium operations", "Event operations manager", "Event day supervisor",
    "Facilities director", "Facilities engineer", "Building engineer", "HVAC technician", "Electrician (venue)",
    "Plumber (venue)", "Carpenter (venue)", "Painter (venue)", "Head groundskeeper", "Groundskeeper",
    "Turf scientist", "Sports field manager", "Golf course superintendent", "Ice technician", "Zamboni driver",
    "Court maintenance technician", "Scoreboard technician", "Video board engineer", "Rigging supervisor", "Stagehand",
    "Conversion crew lead", "Housekeeping manager", "Custodian", "Waste management coordinator", "Sustainability manager",
    "Energy manager", "Parking operations manager", "Parking attendant", "Director of security", "Security guard",
    "Crowd manager", "Emergency management coordinator", "Fire and life safety officer", "Venue booking manager", "Capital projects manager",
  ]],
  ["Food, beverage and hospitality", [
    "Executive chef (stadium)", "Sous chef", "Line cook", "Prep cook", "Pastry chef",
    "Concessions manager", "Concessions stand lead", "Concessions cashier", "Vendor (hawker)", "Beer vendor",
    "Bartender", "Barback", "Suite attendant", "Club level server", "Banquet captain",
    "Catering sales manager", "Catering coordinator", "Premium dining manager", "Restaurant general manager (venue)", "Host",
    "Dishwasher", "Food runner", "Commissary manager", "Warehouse receiver", "Inventory controller",
    "Food safety manager", "Health inspector (stadium)", "Alcohol compliance manager", "Cashless payments manager", "Point-of-sale technician",
    "Menu developer", "Local food partnerships manager", "Signature dish chef", "Food truck operator", "Tailgate caterer",
    "Hospitality director", "Hotel liaison for teams", "Team meal planner", "Press box food service lead", "Hydration station attendant",
  ]],
  ["Transit, travel and logistics", [
    "Director of team travel", "Travel coordinator", "Charter flight coordinator", "Charter pilot", "Flight attendant (team charter)",
    "Team bus driver", "Motor coach dispatcher", "Fleet manager", "Equipment truck driver", "Equipment logistics manager",
    "Freight forwarder (sporting goods)", "Customs broker", "Shipping coordinator", "Warehouse manager", "Warehouse associate",
    "Supply chain analyst", "Procurement manager", "Buyer", "Transit authority event planner", "Shuttle driver",
    "Rideshare operations lead (events)", "Traffic engineer (game day)", "Traffic control officer", "Wayfinding designer", "Bike valet attendant",
    "Rail service planner (event days)", "Ferry operator (waterfront venues)", "Airport team liaison", "Visa and immigration specialist", "Relocation specialist",
    "Hotel room block manager", "Travel agent (sports)", "Tour operator (sports travel)", "Fan travel package manager", "Away-day coordinator",
    "Olympic village logistics manager", "Athlete transport driver", "Horse transport driver", "Yacht captain (sailing team)", "Caravan logistics manager (cycling)",
  ]],
  ["Manufacturing, equipment and apparel", [
    "Footwear designer", "Footwear developer", "Apparel designer", "Technical apparel designer", "Textile engineer",
    "Materials scientist", "Product line manager", "Product tester", "Fit model", "Pattern maker",
    "Sample sewer", "Factory manager", "Production planner", "Quality assurance inspector", "Compliance auditor (factories)",
    "Ball manufacturing technician", "Bat maker", "Glove craftsman", "Helmet engineer", "Protective equipment engineer",
    "Golf club fitter", "Golf club designer", "Racket stringer", "Ski technician", "Bicycle frame builder",
    "Wheel builder", "Boat builder", "Sail maker", "Surfboard shaper", "Skateboard deck manufacturer",
    "Scoreboard manufacturer", "Turf manufacturer", "Gym equipment designer", "Fitness machine technician", "Wearable device engineer",
    "Industrial designer", "Packaging designer", "Prototype machinist", "Sporting goods sales representative", "Trade show manager",
  ]],
  ["Retail and merchandise", [
    "Director of merchandise", "Merchandise manager", "Merchandise buyer", "Merchandise planner", "Team store manager",
    "Team store associate", "Visual merchandiser", "Retail district manager", "E-commerce manager", "E-commerce fulfillment associate",
    "Licensing director", "Licensing manager", "Licensing royalty analyst", "Brand protection investigator", "Anti-counterfeiting specialist",
    "Trading card company product manager", "Trading card authenticator", "Memorabilia authenticator", "Autograph session coordinator", "Memorabilia dealer",
    "Collectibles auction specialist", "Sports card grader", "Game-used equipment manager", "Jersey customization technician", "Embroiderer",
    "Screen printer", "Hat designer", "Jewelry designer (championship rings)", "Ring presentation coordinator", "Souvenir program editor",
    "Pop-up shop manager", "Merchandise stand attendant", "Inventory analyst", "Loss prevention officer", "Retail trainer",
    "Vintage sportswear dealer", "Sneaker reseller", "Sneaker store buyer", "Sporting goods store manager", "Pro shop manager",
  ]],
  ["Technology, data and analytics", [
    "Chief technology officer", "Chief data officer", "Data scientist", "Data engineer", "Machine learning engineer",
    "Quantitative analyst", "Baseball research and development analyst", "Basketball analytics manager", "Football analytics coordinator", "Hockey analytics specialist",
    "Performance analyst", "Opposition analyst", "Tracking data specialist", "Computer vision engineer", "Optical tracking operator",
    "Biomechanics data analyst", "Statistician", "Stats inputter (live)", "Scorekeeping software developer", "Software engineer",
    "Mobile app developer", "Platform engineer", "Site reliability engineer", "Cybersecurity analyst", "IT director",
    "Help desk technician", "Network engineer (venue Wi-Fi)", "Audio-visual systems engineer", "Broadcast IT engineer", "Database administrator",
    "Business intelligence analyst", "Dashboard developer", "GIS analyst (venue and fan mapping)", "Simulation developer", "Virtual reality producer",
    "Augmented reality developer", "Video game developer (sports titles)", "Game designer (sports titles)", "Motion capture technician", "Timing and scoring systems engineer",
  ]],
  ["Medical, health and performance", [
    "Team physician", "Orthopedic surgeon", "Sports medicine physician", "Team dentist", "Team ophthalmologist",
    "Head athletic trainer", "Athletic trainer", "Physical therapist", "Physiotherapist", "Chiropractor",
    "Massage therapist", "Sports psychologist", "Mental performance coach", "Sports psychiatrist", "Counselor (athlete wellness)",
    "Sports dietitian", "Performance nutritionist", "Exercise physiologist", "Biomechanist", "Sports scientist",
    "Sleep specialist", "Recovery specialist", "Hydrotherapy technician", "Cryotherapy technician", "Rehabilitation coordinator",
    "Concussion specialist", "Neuropsychologist", "Independent neurological consultant", "Spotter (concussion protocol)", "Paramedic (event)",
    "Emergency medical technician", "Event physician", "Medical director (marathon)", "Sports podiatrist", "Hand specialist",
    "Vision training specialist", "Yoga instructor (team)", "Pilates instructor (team)", "Personal trainer", "Group fitness instructor",
  ]],
  ["Legal, ethics, integrity and compliance", [
    "General counsel", "Associate general counsel", "Sports lawyer", "Contract attorney", "Labor and employment attorney",
    "Intellectual property attorney", "Immigration attorney (athletes)", "Litigation attorney", "Paralegal", "Compliance director",
    "NCAA compliance officer", "Name, image and likeness compliance officer", "Eligibility specialist", "Title IX coordinator", "Gender equity officer",
    "Integrity officer", "Match-fixing investigator", "Betting integrity analyst", "Anti-corruption investigator", "Ethics officer",
    "Ombudsperson", "Safeguarding officer", "Child protection officer", "Background check specialist", "Independent investigator (misconduct)",
    "Diversity, equity and inclusion director", "Accessibility compliance officer", "Privacy officer", "Data protection officer", "Risk manager",
    "Insurance adjuster (athlete policies)", "Arbitration specialist", "Agent certification administrator", "Rules education coordinator", "Policy writer",
    "Doping control officer", "Therapeutic use exemption reviewer", "Fair play ambassador", "Sports ethicist", "Human rights advisor (mega-events)",
  ]],
  ["Finance, business and administration", [
    "Chief executive officer", "Chief operating officer", "Chief financial officer", "Controller", "Accountant",
    "Payroll specialist", "Accounts payable clerk", "Accounts receivable clerk", "Financial analyst", "Budget analyst",
    "Revenue analyst", "Treasury manager", "Tax manager", "Auditor", "Investor relations manager",
    "Team owner", "Minority owner", "Private equity associate (sports fund)", "Investment banker (sports deals)", "Valuation analyst",
    "Franchise sale advisor", "Business development director", "Strategy director", "Management consultant (sports practice)", "Project manager",
    "Executive assistant", "Office manager", "Receptionist", "Human resources director", "Recruiter",
    "Benefits administrator", "Training and development manager", "Diversity recruiter", "Intern program coordinator", "Administrative assistant",
    "Real estate development director", "Stadium financing specialist", "Public funding analyst", "Economic impact researcher", "Grant writer",
  ]],
  ["Betting, fantasy and gaming", [
    "Sportsbook director", "Oddsmaker", "Trader (sportsbook)", "Risk manager (sportsbook)", "Line setter",
    "In-play trader", "Betting analyst", "Betting content writer", "Handicapper", "Tout",
    "Sportsbook customer service representative", "Responsible gambling manager", "Compliance officer (gaming)", "Geolocation compliance specialist", "Affiliate marketing manager (betting)",
    "Fantasy sports writer", "Fantasy sports analyst", "Fantasy platform product manager", "Daily fantasy contest designer", "Fantasy league commissioner",
    "Prop bet designer", "Betting data feed engineer", "Official data partnership manager", "Odds screen operator", "Casino sportsbook host",
    "Horse racing handicapper", "Pari-mutuel clerk", "Racing steward", "Paddock judge", "Tote operator",
    "Lottery sports product manager", "Prediction market analyst", "Betting exchange engineer", "Sports betting regulator", "Gaming commission investigator",
    "Betting show host", "Picks podcast host", "Betting app UX designer", "Bonus and promotions manager", "Bettor",
  ]],
  ["Esports and emerging sports", [
    "Professional esports player", "Esports team manager", "Esports general manager", "Esports analyst", "Esports caster",
    "Esports observer (in-game camera)", "Esports tournament organizer", "Esports league commissioner", "Esports referee", "Esports event producer",
    "Game publisher esports director", "Esports content creator", "Esports performance coach", "Esports psychologist", "Scrim coordinator",
    "Esports arena manager", "LAN event technician", "Esports broadcast engineer", "Esports sponsorship manager", "Esports talent agent",
    "Drone racing pilot", "Drone racing league operator", "Sim racing driver", "Sim racing engineer", "Pickleball professional",
    "Pickleball league director", "Padel coach", "Spikeball tournament organizer", "Ultimate frisbee professional", "Cornhole professional",
    "Competitive eater", "Chess grandmaster (streamed)", "Speedrunner", "Obstacle course racer", "Parkour athlete",
    "Breaking (breakdance) competitor", "Hyrox athlete", "CrossFit Games athlete", "Slap fighting league official", "Robot combat engineer",
  ]],
  ["Youth, college and community", [
    "Athletic director (college)", "Deputy athletic director", "Senior woman administrator", "Associate athletic director for compliance", "Academic advisor (athletics)",
    "Learning specialist", "Tutor (athletics)", "Life skills coordinator", "Student-athlete development director", "NIL collective director",
    "Collegiate head coach", "Graduate assistant coach", "Recruiting coordinator", "Director of on-campus recruiting", "Walk-on coordinator",
    "High school athletic director", "High school coach", "Physical education teacher", "Adaptive physical education teacher", "Intramural sports coordinator",
    "Campus recreation director", "Club sports coordinator", "Youth league director", "Youth coach", "Camp director",
    "Camp counselor", "Travel team coordinator", "Little League umpire", "Youth soccer referee", "Swim lesson instructor",
    "Lifeguard", "Parks and recreation director", "Recreation center manager", "After-school sports coordinator", "Special Olympics coordinator",
    "Adaptive sports program director", "Wheelchair basketball coach", "Senior games coordinator", "Sports-based youth development director", "Community sports grant manager",
  ]],
  ["Agents, representation and player services", [
    "Sports agent", "Certified contract advisor", "Marketing agent", "Agency president", "Agency recruiter",
    "Contract negotiator", "Financial advisor (athletes)", "Wealth manager (athletes)", "Business manager (athletes)", "Accountant (athletes)",
    "Tax advisor (athletes)", "Estate planner (athletes)", "Athlete brand manager", "Personal publicist", "Personal assistant (athlete)",
    "Driver (athlete)", "Private chef (athlete)", "Personal security (athlete)", "Nanny and family support coordinator", "Relocation concierge",
    "Post-career transition counselor", "Second-career coach", "Athlete education director", "Pre-draft training coordinator", "Combine preparation trainer",
    "Draft advisory consultant", "Insurance broker (athletes)", "Disability insurance specialist", "Image rights lawyer", "Trademark registrar (athlete brands)",
    "Speaking engagements booker", "Appearance coordinator", "Autograph signing agent", "Camp and clinic organizer (athlete-run)", "Charity foundation manager (athlete)",
    "Athlete investment advisor", "Venture scout (athlete fund)", "Podcast producer (athlete-hosted)", "Memoir collaborator", "Family liaison",
  ]],
];

export const JOBS = CATEGORIES.flatMap(([category, titles]) => titles.map(title => ({ category, title })));

// The jobs Worktopia hands out first. Andrew, 2026-10-01: "assign them a
// horrible job. like Postgame Toilet Inspector. Human Cannonball for the
// Cannonball Games." His two, then Claude's.
export const HORRIBLE = [
  "Postgame Toilet Inspector",
  "Human Cannonball for the Cannonball Games",
  "Stadium Seat Gum Remover",
  "Mascot Head Sanitizer",
  "Chewed Sunflower Seed Sweeper",
  "Halftime Confetti Counter",
  "Wet Towel Folder",
  "Human Pylon",
  "Live Tackling Dummy",
  "Field Goal Net Climber",
  "Pigeon Discourager",
  "Shin Guard Odor Technician",
  "Sweat Collection Specialist",
  "Overflow Lot Cone Placer",
  "Press Box Microwave Cleaner",
  "Cooler Scrubber",
  "Rosin Bag Refiller",
  "Pine Tar Remover",
  "Laundry Attendant, Hockey Division",
  "Vuvuzela Tuner",
  "Luxury Suite Crumb Vacuumer",
  "Nosebleed Section Stair Counter",
  "Jumbotron Pixel Checker",
  "Goalpost Padding Hugger",
  "Rain Delay Tarp Puller",
  "Mascot Understudy's Understudy",
  "Beer Snake Dismantler",
  "Hot Dog Launcher Reloader",
  "Outdoor Loose Ball Chaser",
  "Human Shot Clock",
  "Manual Instant Replay Rewinder",
  "Escalator Step Polisher",
  "Locker Room Air Freshener",
  "Dugout Spit Zone Monitor",
  "Foam Finger Quality Control",
  "Eye Black Applicator",
  "Athlete Nail Clipper",
  "Team Bus Snack Wrapper Collector",
  "Ice Bath Temperature Tester (by hand)",
  "Golf Ball Pond Diver",
  "Marathon Orange Slice Cutter",
  "Ski Lift Chair De-icer",
  "Bowling Shoe Disinfector",
  "Wrestling Mat Scrubber",
  "Rowing Boat Bailer",
  "Swim Lane Rope Untangler",
  "Racetrack Manure Analyst",
  "Ball Pump Operator",
  "Overtime Parking Attendant",
  "Celebrity Row Umbrella Holder",
  "Tailgate Grill Scraper",
  "Human Tee for the Kicking League",
  "Cannonball Net Holder",
  "Fourth Quarter Blowout Crowd Warmer",
  "Replay Review Chair Warmer",
  "Bullpen Phone Answerer",
  "Robot Tennis League Ball Retriever",
  "Stadium Cup Holder Inspector",
  "Halftime Show Cable Untangler",
  "Trophy Fingerprint Polisher",
];

// The horrible job for a name, by round: the name picks where in the list to
// start, and each refusal to decline moves one along.
export const horribleFor = (h, round) => HORRIBLE[(h % HORRIBLE.length + round) % HORRIBLE.length];

// Lower case, no parentheses, no punctuation, and no plural s, so "highlight
// editor" finds "Highlights editor".
const norm = (s) => String(s || "").toLowerCase().replace(/\(.*?\)/g, " ").replace(/[^a-z0-9]+/g, " ").trim().split(" ").map(w => w.length > 3 ? w.replace(/s$/, "") : w).join(" ");
/** The Index entry for a typed title: an exact match, else one that contains it, else null. */
export const findJob = (title) => {
  const q = norm(title);
  if (!q) return null;
  return JOBS.find(j => norm(j.title) === q) || JOBS.find(j => norm(j.title).includes(q) || q.includes(norm(j.title))) || null;
};
